### PR TITLE
Revert "Add pause functionality so we can do actual archiving of the data"

### PR DESCRIPTION
**Pull request by zackkitzmiller**
Reverts seatgeek/sixpack#200

### CODE REVIEW

**Comment by johnbacon** [comment]
@zackkitzmiller: Was there an issue with this that we could possibly help fix? I'd love to have this functionality in Sixpack long-term.

**Comment by johnbacon** [comment]
We have about 500Mb free, with Redis using 2.2Gb, on our dedicated Sixpack server. If this commit is ultimately reverted I'm concerned we'll have to fork Sixpack in order for it to be feasible for us to continue using it.

**Comment by josegonzalez** [comment]
@zackkitzmiller *bump*

**Comment by zackkitzmiller** [comment]
@johnbacon We can leave this in.

**Comment by johnbacon** [comment]
@josegonzalez @zackkitzmiller This functionality has been merged for over 10 months, but there has not been an official release of Sixpack in over a year. Are there any plans for a new release of Sixpack in the near future?

**Pull request closed without merging**
