### PR TITLE
Add option to record forced experiment

### PR DESCRIPTION
**Pull request by dbillingham**
Merged these changes into the latest version of master:
https://github.com/seatgeek/sixpack/pull/248

### CODE REVIEW

**Comment by zackkitzmiller** [comment]
@dbillingham happy to consider this, but do you mind adding a test?

**Comment by dbillingham** [comment]
thanks @zackkitzmiller, test added :)

**Comment by dbillingham** [comment]
hi @zackkitzmiller , is there anything else I can do to help push this through :)
Ive created a demo here: https://www.screencast.com/t/d59vugOxsY7

**Comment by zackkitzmiller** [comment]
@dbillingham I'll take a look at this later this week. Hopefully I can get it out and release it for you before the holiday.

**Comment by dbillingham** [comment]
ace, thanks for your help @zackkitzmiller :)

**Comment by zackkitzmiller** [comment]
@dbillingham just cut this release.

**Pull request merged**
