### PR TITLE
Add pause functionality so we can do actual archiving of the data

### PR DESCRIPTION
**Pull request by nickveenhof**
See #199 for details on this PR

### CODE REVIEW

**Comment by nickveenhof** [comment]
Added more tests so at least code coverage didn't drop.

**Comment by zackkitzmiller** [comment]
Cool. Thanks for the PR. I'm going to think on this one for a while. It seems like additional functionality for a very specific use case.

**Comment by nickveenhof** [comment]
Ok, sounds good. Just keep in mind that this saves us a lot of memory in our daily operation for tests that are finished and you want to keep overal stats. It will allow cost-reduction to your servers as well since having redis-servers could be quite expensive when there is no possible way to clean-up your data without losing important statistics. I thought about some export functionality also but that would perhaps be even more out of scope?

**Comment by zackkitzmiller** [comment]
There actually is some export functionality built it, but it might be pretty primative.

**Comment by johnbacon** [comment]
If I'm understanding this pull request properly, +1 to it.

We're at the point where we have to export and delete experiments from Sixpack just to keep the server operational. This is highly inoptimal and means having to figure out a way to export and archive the old data ourselves, including the conversion rates for multiple KPIs, something the _Export_ feature doesn't make easy.

**Comment by nickveenhof** [comment]
I think we have been using this for a while now. Working well for us. More testers would be totally awesome

**Comment by johnbacon** [comment]
@nickveenhof That's great to hear, and we'd love to implement it if it solved our problems. Do you have a fork with the latest Sixpack changes also incorporated, or has your team been using it with an older version?

What would be best is if Sixpack were open to accepting the pull request. If need be, we could always (temporarily?) create a Sevenpack fork for those who need this functionality.

**Comment by zackkitzmiller** [comment]
Hey hey. Will take a look later today.

**Comment by zackkitzmiller** [comment]
I think this patch looks reasonable. I do think we will have to do a Major version release here though, because we're dramatically changing the archive behavior. Thoughts?

**Comment by johnbacon** [comment]
@zackkitzmiller My only thought is being super happy this will possibly be merged. This makes Sixpack much more manageable for us in the long run. Thanks for taking a look!

**Comment by johnbacon** [comment]
This has been merged for a significant amount of time but no new releases of Sixpack have happened in the interim. @zackkitzmiller, is there any work I could do to help make this happen? (We've been clearing out old tests in the interim, but that isn't the best solution...)

**Comment by johnbacon** [comment]
@josegonzalez @zackkitzmiller This functionality has been merged for over 10 months, but there has not been an official release of Sixpack in over a year. Are there any plans for a new release of Sixpack in the near future?

I greatly appreciate the work you're doing with Sixpack. We're still handling this by deleting "archived" experiments to free up space.

**Comment by zackkitzmiller** [comment]
@johnbacon Yup! (I don't know how I missed the message from May). I should be able to get a release out for you this week.

**Comment by zackkitzmiller** [comment]
@johnbacon released 2.4.0.

**Pull request merged**
